/**********************************************************************
 * Extern for domvm
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var domvm = {
  "_views": {},
  "ViewModel": function () {},
  "VNode": function () {},
  "createView": function () {},
  "defineElement": function () {},
  "defineText": function () {},
  "defineComment": function () {},
  "defineFragment": function () {},
  "defineView": function () {},
  "injectView": function () {},
  "injectElement": function () {},
  "FIXED_BODY": {},
  "FAST_REMOVE": {},
  "KEYED_LIST": {},
  "h": function () {},
  "defineElementSpread": function () {}
};
domvm.ViewModel.prototype = {
  "constructor": function () {},
  "id": function () {},
  "view": function () {},
  "key": function () {},
  "model": function () {},
  "opts": function () {},
  "node": function () {},
  "hooks": function () {},
  "render": function () {},
  "parent": function () {},
  "root": function () {},
  "api": function () {},
  "refs": function () {},
  "mount": function () {},
  "unmount": function () {},
  "redraw": function () {},
  "update": function () {},
  "_update": function () {},
  "_redraw": function () {},
  "_redrawAsync": function () {},
  "_updateAsync": function () {},
  "hook": function () {},
  "_diff": function () {},
  "diff": function () {}
};
domvm.VNode.prototype = {
  "constructor": function () {},
  "type": function () {},
  "vm": function () {},
  "vmid": function () {},
  "key": function () {},
  "ref": function () {},
  "data": function () {},
  "hooks": function () {},
  "raw": function () {},
  "el": function () {},
  "tag": function () {},
  "attrs": function () {},
  "body": function () {},
  "flags": function () {},
  "_class": function () {},
  "idx": function () {},
  "parent": function () {},
  "flatIdx": function () {},
  "flatParent": function () {},
  "flatBody": function () {},
  "patch": function () {}
};
/**********************************************************************
 * End Generated Extern for domvm
/**********************************************************************/
